In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Grouped aggregation via GroupbySeries
frame.groupby("Ship Name")["Order Id"].sum().head().to_pandas()

                            Ship Name  Order Id
0                Alfred's Futterkiste     54192
1                 Alfreds Futterkiste     10643
2  Ana Trujillo Emparedados y helados     42618
3             Antonio Moreno Taquería     74195
4                     Around the Horn    139254

In [1]:
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Assign a grouped rank back to the frame
frame["Order Rank"] = frame.groupby("Ship Name")["Order Id"].rank()
frame.head(5).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,Order Rank
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,1
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,1
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,1
3,10251,1996-07-08,1996-08-05,1996-07-15,Victuailles en stock,1
4,10252,1996-07-09,1996-08-06,1996-07-11,Suprêmes délices,1

In [1]:
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Arithmetic with a grouped rank
frame["Grouped Rank"] = frame.groupby(
    "Ship Name"
)["Order Id"].rank()
frame.head(5).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,Grouped Rank
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,1
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,1
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,1
3,10251,1996-07-08,1996-08-05,1996-07-15,Victuailles en stock,1
4,10252,1996-07-09,1996-08-06,1996-07-11,Suprêmes délices,1