In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Sort by a single column (ascending by default)
frame.sort_values("Ship Name").head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     11011 1998-04-09    1998-05-07   1998-04-13  Alfred's Futterkiste
1     10702 1997-10-13    1997-11-24   1997-10-21  Alfred's Futterkiste
2     10692 1997-10-03    1997-10-31   1997-10-13  Alfred's Futterkiste
3     10952 1998-03-16    1998-04-27   1998-03-24  Alfred's Futterkiste
4     10835 1998-01-15    1998-02-12   1998-01-21  Alfred's Futterkiste

In [1]:
# Sort descending
frame.sort_values("Order Id", ascending=False).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date                   Ship Name
0     11077 1998-05-06    1998-06-03          NaT  Rattlesnake Canyon Grocery
1     11076 1998-05-06    1998-06-03          NaT                    Bon app'
2     11075 1998-05-06    1998-06-03          NaT          Richter Supermarkt
3     11074 1998-05-06    1998-06-03          NaT               Simons bistro
4     11073 1998-05-05    1998-06-02          NaT   Pericles Comidas clásicas

In [1]:
# Sort by multiple columns with mixed directions
frame.sort_values(
    by=["Ship Name", "Order Id"],
    ascending=[True, False]
).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     11011 1998-04-09    1998-05-07   1998-04-13  Alfred's Futterkiste
1     10952 1998-03-16    1998-04-27   1998-03-24  Alfred's Futterkiste
2     10835 1998-01-15    1998-02-12   1998-01-21  Alfred's Futterkiste
3     10702 1997-10-13    1997-11-24   1997-10-21  Alfred's Futterkiste
4     10692 1997-10-03    1997-10-31   1997-10-13  Alfred's Futterkiste