In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Get rows 0-4 (first 5 rows)
frame.slice(0, 5).to_pandas()

   Order Id Order Date Required Date Shipped Date                  Ship Name
0     10248 1996-07-04    1996-08-01   1996-07-16  Vins et alcools Chevalier
1     10249 1996-07-05    1996-08-16   1996-07-10         Toms Spezialitäten
2     10250 1996-07-08    1996-08-05   1996-07-12              Hanari Carnes
3     10251 1996-07-08    1996-08-05   1996-07-15       Victuailles en stock
4     10252 1996-07-09    1996-08-06   1996-07-11           Suprêmes délices

In [1]:
# Get rows 5-9
frame.slice(5, 10).to_pandas()

   Order Id Order Date Required Date Shipped Date               Ship Name
0     10253 1996-07-10    1996-07-24   1996-07-16           Hanari Carnes
1     10254 1996-07-11    1996-08-08   1996-07-23       Chop-suey Chinese
2     10255 1996-07-12    1996-08-09   1996-07-15      Richter Supermarkt
3     10256 1996-07-15    1996-08-12   1996-07-17  Wellington Importadora
4     10257 1996-07-16    1996-08-13   1996-07-22        HILARION-Abastos

In [1]:
# Get rows 2-6
frame.slice(2, 7).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     10250 1996-07-08    1996-08-05   1996-07-12         Hanari Carnes
1     10251 1996-07-08    1996-08-05   1996-07-15  Victuailles en stock
2     10252 1996-07-09    1996-08-06   1996-07-11      Suprêmes délices
3     10253 1996-07-10    1996-07-24   1996-07-16         Hanari Carnes
4     10254 1996-07-11    1996-08-08   1996-07-23     Chop-suey Chinese