In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Add a single window function column
win = frame.window(partition_by="Ship Name", order_by="Order Id")
frame.window_extend(
    win,
    ("RowNumber", lambda p, w, r: p.row_number(r))
).select(
    ["Ship Name", "Order Id", "RowNumber"]
).head(5).to_pandas()

                   Ship Name  Order Id  RowNumber
0  Vins et alcools Chevalier     10248          1
1         Toms Spezialitäten     10249          1
2              Hanari Carnes     10250          1
3       Victuailles en stock     10251          1
4           Suprêmes délices     10252          1

In [1]:
# Add basic window function columns
frame.window_extend(
    frame.window(partition_by="Ship Name", order_by="Order Id"),
    [
        ("RowNumber", lambda p, w, r: p.row_number(r)),
        ("Rank", lambda p, w, r: p.rank(w, r))
    ]
).select(
   ["Ship Name", "Order Id", "RowNumber", "Rank"]
).head(5).to_pandas()

                   Ship Name  Order Id  RowNumber  Rank
0  Vins et alcools Chevalier     10248          1     1
1         Toms Spezialitäten     10249          1     1
2              Hanari Carnes     10250          1     1
3       Victuailles en stock     10251          1     1
4           Suprêmes délices     10252          1     1