In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Get distinct values for a single column
frame.distinct("Ship Name").head(10).to_pandas()

                   Ship Name
0          Chop-suey Chinese
1               Ernst Handel
2           HILARION-Abastos
3              Hanari Carnes
4         Richter Supermarkt
5           Suprêmes délices
6         Toms Spezialitäten
7       Victuailles en stock
8  Vins et alcools Chevalier
9     Wellington Importadora

In [1]:
# Get distinct combinations of multiple columns
frame.distinct(["Ship Name", "Order Date"]).head(10).to_pandas()

                   Ship Name Order Date
0          Chop-suey Chinese 1996-07-11
1           HILARION-Abastos 1996-07-16
2              Hanari Carnes 1996-07-08
3              Hanari Carnes 1996-07-10
4         Richter Supermarkt 1996-07-12
5           Suprêmes délices 1996-07-09
6         Toms Spezialitäten 1996-07-05
7       Victuailles en stock 1996-07-08
8  Vins et alcools Chevalier 1996-07-04
9     Wellington Importadora 1996-07-15

In [1]:
# Using a callable to specify columns
frame.distinct(lambda r: [r["Ship Name"], r["Order Date"]]).head(10).to_pandas()

                   Ship Name Order Date
0          Chop-suey Chinese 1996-07-11
1           HILARION-Abastos 1996-07-16
2              Hanari Carnes 1996-07-08
3              Hanari Carnes 1996-07-10
4         Richter Supermarkt 1996-07-12
5           Suprêmes délices 1996-07-09
6         Toms Spezialitäten 1996-07-05
7       Victuailles en stock 1996-07-08
8  Vins et alcools Chevalier 1996-07-04
9     Wellington Importadora 1996-07-15