In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Rename a single column
frame.rename(("Ship Name", "Vessel Name")).head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date                Vessel Name
0     10248 1996-07-04    1996-08-01   1996-07-16  Vins et alcools Chevalier
1     10249 1996-07-05    1996-08-16   1996-07-10         Toms Spezialitäten
2     10250 1996-07-08    1996-08-05   1996-07-12              Hanari Carnes

In [1]:
# Rename multiple columns
frame.rename(
    [("Ship Name", "Vessel Name"), ("Order Date", "Date Ordered")]
).head(3).to_pandas()

   Order Id Date Ordered Required Date Shipped Date                Vessel Name
0     10248   1996-07-04    1996-08-01   1996-07-16  Vins et alcools Chevalier
1     10249   1996-07-05    1996-08-16   1996-07-10         Toms Spezialitäten
2     10250   1996-07-08    1996-08-05   1996-07-12              Hanari Carnes

In [1]:
# Using a callable to rename columns
frame.rename(lambda r: (r["Ship Name"], "Vessel Name")).head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date                Vessel Name
0     10248 1996-07-04    1996-08-01   1996-07-16  Vins et alcools Chevalier
1     10249 1996-07-05    1996-08-16   1996-07-10         Toms Spezialitäten
2     10250 1996-07-08    1996-08-05   1996-07-12              Hanari Carnes