In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Project single column (copy with new name)
frame.project(("Order Number", lambda r: r["Order Id"])).head(5).to_pandas()

   Order Number
0         10248
1         10249
2         10250
3         10251
4         10252

In [1]:
# Project multiple columns with transformations
frame.project([
    ("Order Number", lambda r: r["Order Id"]),
    ("Vessel", lambda r: r["Ship Name"].upper()),
    ("Vessel Lower", lambda r: r["Ship Name"].lower())
]).head(5).to_pandas()

   Order Number                     Vessel               Vessel Lower
0         10248  VINS ET ALCOOLS CHEVALIER  vins et alcools chevalier
1         10249         TOMS SPEZIALITÄTEN         toms spezialitäten
2         10250              HANARI CARNES              hanari carnes
3         10251       VICTUAILLES EN STOCK       victuailles en stock
4         10252           SUPRÊMES DÉLICES           suprêmes délices

In [1]:
# Project with existing column values
frame.project([
    ("ID", lambda r: r["Order Id"]),
    ("Name", lambda r: r["Ship Name"]),
    ("Date", lambda r: r["Order Date"])
]).head(5).to_pandas()

      ID                       Name       Date
0  10248  Vins et alcools Chevalier 1996-07-04
1  10249         Toms Spezialitäten 1996-07-05
2  10250              Hanari Carnes 1996-07-08
3  10251       Victuailles en stock 1996-07-08
4  10252           Suprêmes délices 1996-07-09