In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Single aggregation
frame.aggregate(
    ("Total Orders", lambda r: r["Order Id"], lambda c: c.count())
).to_pandas()

   Total Orders
0           830

In [1]:
# Multiple aggregations
frame.aggregate([
    ("Total Orders", lambda r: r["Order Id"], lambda c: c.count()),
    ("Min Order Id", lambda r: r["Order Id"], lambda c: c.min()),
    ("Max Order Id", lambda r: r["Order Id"], lambda c: c.max())
]).to_pandas()

   Total Orders  Min Order Id  Max Order Id
0           830         10248         11077