In [1]:
import pylegend
import numpy as np
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Aggregate a single column with a string function
frame.aggregate({"Order Id": "count"}).to_pandas()

   Order Id
0       830

In [1]:
# Aggregate multiple columns with different functions
frame.aggregate({"Order Id": "min", "Ship Name": "count"}).to_pandas()

   Order Id  Ship Name
0     10248        830

In [1]:
# Broadcast a single function to all columns
frame.aggregate("count").to_pandas()

   Order Id  Order Date  Required Date  Shipped Date  Ship Name
0       830         830            830           809        830

In [1]:
# Use a lambda for custom aggregation
frame.aggregate({
    "Order Id": lambda x: x.max(),
    "Order Date": np.min,
    "Order Date": np.max,
    "Shipped Date": "min"
}).to_pandas()

   Order Id Order Date Shipped Date
0     11077 1998-05-06   1996-07-10