In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Select specific columns by name
frame.filter(items=["Order Id", "Ship Name"]).head(3).to_pandas()

   Order Id                  Ship Name
0     10248  Vins et alcools Chevalier
1     10249         Toms Spezialitäten
2     10250              Hanari Carnes

In [1]:
# Select columns whose names contain a substring
frame.filter(like="Ship").head(3).to_pandas()

  Shipped Date                  Ship Name
0   1996-07-16  Vins et alcools Chevalier
1   1996-07-10         Toms Spezialitäten
2   1996-07-12              Hanari Carnes

In [1]:
# Select columns matching a regex pattern
frame.filter(regex="^Ship").head(3).to_pandas()

  Shipped Date                  Ship Name
0   1996-07-16  Vins et alcools Chevalier
1   1996-07-10         Toms Spezialitäten
2   1996-07-12              Hanari Carnes

In [1]:
# Chain filters to progressively narrow columns
frame.filter(like="Ship").filter(regex="Name$").head(3).to_pandas()

                   Ship Name
0  Vins et alcools Chevalier
1         Toms Spezialitäten
2              Hanari Carnes