In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Drop a single column
frame.drop(columns="Ship Name").head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date
0     10248 1996-07-04    1996-08-01   1996-07-16
1     10249 1996-07-05    1996-08-16   1996-07-10
2     10250 1996-07-08    1996-08-05   1996-07-12

In [1]:
# Drop multiple columns
frame.drop(columns=["Ship Name", "Order Date"]).head(3).to_pandas()

   Order Id Required Date Shipped Date
0     10248    1996-08-01   1996-07-16
1     10249    1996-08-16   1996-07-10
2     10250    1996-08-05   1996-07-12

In [1]:
# Using labels parameter
frame.drop(labels=["Ship Name"], axis=1).head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date
0     10248 1996-07-04    1996-08-01   1996-07-16
1     10249 1996-07-05    1996-08-16   1996-07-10
2     10250 1996-07-08    1996-08-05   1996-07-12

In [1]:
# Ignore missing columns instead of raising an error
frame.drop(columns=["Ship Name", "NonExistent"], errors="ignore").head(3).to_pandas()

   Order Id Order Date Required Date Shipped Date
0     10248 1996-07-04    1996-08-01   1996-07-16
1     10249 1996-07-05    1996-08-16   1996-07-10
2     10250 1996-07-08    1996-08-05   1996-07-12