In [1]:
import pylegend
frame = pylegend.samples.pandas_api.northwind_orders_frame()

In [1]:
# Classify orders by size
frame["size"] = (frame["Order Id"] > 10250).case("large", "small")
frame.head(5).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,size
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,small
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,small
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,small
3,10251,1996-07-08,1996-08-05,1996-07-15,Victuailles en stock,large
4,10252,1996-07-09,1996-08-06,1996-07-11,Suprêmes délices,large

In [1]:
# Numeric branch — compute a bonus
frame["bonus"] = (frame["Order Id"] > 10250).case(100, 0)
frame.head(5).to_pandas()

,Order Id,Order Date,Required Date,Shipped Date,Ship Name,size,bonus
0,10248,1996-07-04,1996-08-01,1996-07-16,Vins et alcools Chevalier,small,0
1,10249,1996-07-05,1996-08-16,1996-07-10,Toms Spezialitäten,small,0
2,10250,1996-07-08,1996-08-05,1996-07-12,Hanari Carnes,small,0
3,10251,1996-07-08,1996-08-05,1996-07-15,Victuailles en stock,large,100
4,10252,1996-07-09,1996-08-06,1996-07-11,Suprêmes délices,large,100