In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Select a single column
frame.select("Ship Name").head(5).to_pandas()

                   Ship Name
0  Vins et alcools Chevalier
1         Toms Spezialitäten
2              Hanari Carnes
3       Victuailles en stock
4           Suprêmes délices

In [1]:
# Select multiple columns
frame.select(["Order Id", "Ship Name", "Order Date"]).head(5).to_pandas()

   Order Id                  Ship Name Order Date
0     10248  Vins et alcools Chevalier 1996-07-04
1     10249         Toms Spezialitäten 1996-07-05
2     10250              Hanari Carnes 1996-07-08
3     10251       Victuailles en stock 1996-07-08
4     10252           Suprêmes délices 1996-07-09

In [1]:
# Using a callable to select columns
frame.select(lambda r: [r["Order Id"], r["Ship Name"]]).head(5).to_pandas()

   Order Id                  Ship Name
0     10248  Vins et alcools Chevalier
1     10249         Toms Spezialitäten
2     10250              Hanari Carnes
3     10251       Victuailles en stock
4     10252           Suprêmes délices