In [1]:
import pylegend
frame = pylegend.samples.legendql_api.northwind_orders_frame()

In [1]:
# Sort by single column (ascending by default)
frame.sort("Ship Name").head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     10835 1998-01-15    1998-02-12   1998-01-21  Alfred's Futterkiste
1     11011 1998-04-09    1998-05-07   1998-04-13  Alfred's Futterkiste
2     10952 1998-03-16    1998-04-27   1998-03-24  Alfred's Futterkiste
3     10692 1997-10-03    1997-10-31   1997-10-13  Alfred's Futterkiste
4     10702 1997-10-13    1997-11-24   1997-10-21  Alfred's Futterkiste

In [1]:
# Sort by multiple columns (all ascending)
frame.sort(["Ship Name", "Order Date"]).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     10692 1997-10-03    1997-10-31   1997-10-13  Alfred's Futterkiste
1     10702 1997-10-13    1997-11-24   1997-10-21  Alfred's Futterkiste
2     10835 1998-01-15    1998-02-12   1998-01-21  Alfred's Futterkiste
3     10952 1998-03-16    1998-04-27   1998-03-24  Alfred's Futterkiste
4     11011 1998-04-09    1998-05-07   1998-04-13  Alfred's Futterkiste

In [1]:
# Sort with explicit direction using callable
frame.sort(lambda r: r["Ship Name"].descending()).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date      Ship Name
0     10611 1997-07-25    1997-08-22   1997-08-01  Wolski Zajazd
1     10374 1996-12-05    1997-01-02   1996-12-09  Wolski Zajazd
2     10998 1998-04-03    1998-04-17   1998-04-17  Wolski Zajazd
3     10792 1997-12-23    1998-01-20   1997-12-31  Wolski Zajazd
4     10906 1998-02-25    1998-03-11   1998-03-03  Wolski Zajazd

In [1]:
# Sort by multiple columns with different directions
frame.sort(
    lambda r: [r["Ship Name"].ascending(), r["Order Id"].descending()]
).head(5).to_pandas()

   Order Id Order Date Required Date Shipped Date             Ship Name
0     11011 1998-04-09    1998-05-07   1998-04-13  Alfred's Futterkiste
1     10952 1998-03-16    1998-04-27   1998-03-24  Alfred's Futterkiste
2     10835 1998-01-15    1998-02-12   1998-01-21  Alfred's Futterkiste
3     10702 1997-10-13    1997-11-24   1997-10-21  Alfred's Futterkiste
4     10692 1997-10-03    1997-10-31   1997-10-13  Alfred's Futterkiste